HOSTS:
  centos-64-x64.local:
    roles:
      - master
      - agent
      - dashboard
      - database
    platform: el-6-i386
    box : centos-64-x64-vbox4210-nocm
    box_url : http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box
    hypervisor : vagrant
    pe_dir : http://neptune.puppetlabs.lan/archives/releases/3.1.2/
